<?php

use Drupal\user\UserInterface;
use \Drupal\Core\Link;

/**
 * Implements hook_ENTITY_TYPE_presave().
 *
 * If a user opts-in to volunteer questionnaires, then the sign-up
 * questionnaire is immediately added to their list of requested
 * questionnaires.
 *
 * @param Drupal\user\UserInterface $user
 *   User account being saved.
 */
function volunteer_questionnaires_user_presave(UserInterface $user) {
  $originalOptInValue = isset($user->original) ? $user->original->field_questionnaire_opt_in->value : FALSE;
  $newOptinValue = $user->field_questionnaire_opt_in->value;

  if ($originalOptInValue !== $newOptinValue) {
    if ($newOptinValue) {
      // Opt-in so request the user fills in the initial sign-up form.
      $config = \Drupal::config('volunteer_questionnaires.settings');
      $webformId = $config->get('signup_webform_id');
      if ($webformId) {
        $user->get('field_requested_questionnaires')->setValue([['target_id' => $webformId]]);
        $webform = \Drupal::entityTypeManager()->getStorage('webform')->load($webformId);
        \Drupal::messenger()->addMessage(t('Thank you for participating in the volunteer questionnaires. There is one questionnaire ready for you to complete: <a href=":url">@title</a>', [
          ':url' => $webform->toUrl(),
          '@title' => $webform->get('title'),
        ]));
      }
      else {
        \Drupal::messenger()->addMessage(t('Thank you for participating in the volunteer questionnaires.'));
      }
    }
    else {
      // Clear the forms as the user is opting out.
      $user->get('field_requested_questionnaires')->setValue([]);
    }
  }
}

/**
 * Implements hook_theme().
 *
 * Declares a template for the requested forms block output.
 */
function volunteer_questionnaires_theme() {
  return [
    'block__volunteer_questionnaires_requested_forms' => [
      'variables' => ['items' => NULL],
      'template' => 'block--volunteer-questionnaires-requested-forms',
    ],
  ];
}